import { expect, it } from 'vitest';
import { stringifySyml } from '@yarnpkg/parsers';
import { restoreDescriptorHeaders } from '../../main/ts/patch.js';
import { descriptors, parseLockfile, type Lockfile } from '../../main/ts/lockfile.js';
import type { Change } from '../../main/ts/plan.js';

const record = (version = '1.2.3') => ({
  version, resolution: `foo@npm:${version}`, checksum: 'keep-this-checksum',
  dependencies: { child: 'npm:^2' }, peerDependencies: { peer: '^3' },
  dependenciesMeta: { child: { optional: true } }, linkType: 'hard',
});
const parent = (range: string) => ({ version: '1.0.0', resolution: `parent-${range}@workspace:.`, dependencies: { foo: range } });
const change: Change = { name: 'foo', descriptor: 'foo@npm:^1', from: '1.0.0', to: '1.2.3' };
const text = (entries: Lockfile) => '# Generated by Yarn\n\n' + stringifySyml({ __metadata: { version: '8', cacheKey: '10' }, ...entries });

it.each(['npm:^1', '^1'])('patches only a header for a %s declaration, preserving the package payload', range => {
  const generated = text({ 'foo@npm:1.2.3': record(), 'parent@workspace:.': parent(range) });
  expect(restoreDescriptorHeaders(generated, [change])).toBe(generated.replace('"foo@npm:1.2.3":', '"foo@npm:^1":'));
});

it('groups multiple original requests without losing a real exact pin or an existing alias', () => {
  const generated = text({
    'foo@npm:1.2.3, foo@npm:^1.2.1': record(),
    'a@workspace:a': parent('npm:^1'),
    'b@workspace:b': parent('npm:~1.2.0'),
    'c@workspace:c': parent('npm:1.2.3'),
    'd@workspace:d': parent('npm:^1.2.1'),
  });
  const patched = parseLockfile(restoreDescriptorHeaders(generated, [change, { ...change, descriptor: 'foo@npm:~1.2.0' }]));
  expect(patched['foo@npm:1.2.3, foo@npm:^1, foo@npm:^1.2.1, foo@npm:~1.2.0']).toEqual(parseLockfile(generated)['foo@npm:1.2.3, foo@npm:^1.2.1']);
});

it('keeps a new exact pin introduced by an upgraded parent and does not restore its obsolete range', () => {
  const generated = text({ 'foo@npm:1.2.3': record(), 'parent@workspace:.': parent('npm:1.2.3') });
  expect(restoreDescriptorHeaders(generated, [change])).toBe(generated);
});

it('does not resurrect an old request when its parent removed the dependency', () => {
  const generated = text({ 'parent@workspace:.': { version: '2.0.0', resolution: 'parent@workspace:.' } });
  expect(restoreDescriptorHeaders(generated, [change])).toBe(generated);
});

it('sorts renamed records in Yarn order without changing their bodies', () => {
  const generated = text({
    'foo@npm:1.2.3': record(), 'foo@npm:2.0.0': record('2.0.0'),
    'a@workspace:a': parent('npm:^1'), 'b@workspace:b': parent('npm:>=1'),
  });
  const patched = restoreDescriptorHeaders(generated, [change, { ...change, descriptor: 'foo@npm:>=1', to: '2.0.0' }]);
  expect(patched.indexOf('"foo@npm:>=1":')).toBeLessThan(patched.indexOf('"foo@npm:^1":'));
  const entries = descriptors(parseLockfile(patched));
  expect(entries.get('foo@npm:^1')).toEqual(parseLockfile(generated)['foo@npm:1.2.3']);
  expect(entries.get('foo@npm:>=1')).toEqual(parseLockfile(generated)['foo@npm:2.0.0']);
});

it('preserves CRLF line endings', () => {
  const generated = text({ 'foo@npm:1.2.3': record(), 'parent@workspace:.': parent('npm:^1') }).replaceAll('\n', '\r\n');
  expect(restoreDescriptorHeaders(generated, [change])).toBe(generated.replace('"foo@npm:1.2.3":', '"foo@npm:^1":'));
});

it('rejects incompatible replacements and missing generated targets', () => {
  const generated = text({ 'foo@npm:1.2.3': record(), 'parent@workspace:.': parent('npm:^1') });
  expect(() => restoreDescriptorHeaders(generated, [{ ...change, to: '2.0.0' }])).toThrow('Incompatible');
  expect(() => restoreDescriptorHeaders(generated, [{ ...change, to: '1.2.4' }])).toThrow('did not produce');
});

it('rejects conflicting descriptor aliases instead of overwriting another record', () => {
  const generated = text({ 'foo@npm:1.2.3': record(), 'foo@npm:^1': record('1.0.0'), 'parent@workspace:.': parent('npm:^1') });
  expect(() => restoreDescriptorHeaders(generated, [change])).toThrow('Conflicting descriptor');
});

it('leaves the file untouched when no changes were planned', () => {
  expect(restoreDescriptorHeaders('unparsed content', [])).toBe('unparsed content');
});

it('emits valid explicit YAML keys when restored ranges exceed the simple-key limit', () => {
  const changes = Array.from({ length: 70 }, (_, i) => ({ ...change, descriptor: `foo@npm:>=1.0.${i} <2` }));
  const parents = Object.fromEntries(changes.map((item, i) => [`parent-${i}@workspace:${i}`, parent(item.descriptor.slice('foo@'.length))]));
  const generated = text({ 'foo@npm:1.2.3': record(), ...parents });
  const restored = restoreDescriptorHeaders(generated, changes);
  const combined = changes.map(item => item.descriptor).sort().join(', ');
  expect(restored).toContain(`? ${JSON.stringify(combined)}\n:\n`);
  expect(parseLockfile(restored)[combined]).toEqual(parseLockfile(generated)['foo@npm:1.2.3']);
  expect(restored).toBe(text({ [combined]: record(), ...parents }));
});

it.each(['? "other@npm:^1"\n:', '?\n  "other@npm:^1"\n:'])('preserves an unrelated explicit key: %s', header => {
  const generated = text({ 'foo@npm:1.2.3': record(), 'other@npm:^1': { version: '1.0.0', resolution: 'other@npm:1.0.0' }, 'parent@workspace:.': parent('npm:^1') })
    .replace('"other@npm:^1":', header);
  expect(restoreDescriptorHeaders(generated, [change])).toBe(generated.replace('"foo@npm:1.2.3":', '"foo@npm:^1":'));
});
